import type { CategoryId } from './types'

// Sample content derived from the 26-week brief, flattened into topics per category.
// Editable in the app; this list is only used to seed an empty account.
export const SEED_TOPICS: Record<CategoryId, string[]> = {
  technique: [
    'Even fingerstyle on one string',
    'Silencing unused strings',
    'Alternating fingers across adjacent strings',
    'Controlling note endings',
    'Slides',
    'Hammer-ons and pull-offs',
    'Sixteenths and ghost notes',
    'Controlled speed, economical string crossing',
    'Slap: thumb attack and muting',
    'Slap: octave pops',
    'Funk articulation: accents and note lengths',
    'Connecting arpeggios across positions',
  ],
  theory: [
    'Open-string names and octaves',
    'Locating roots in a song',
    'Root, third and fifth',
    'Major and minor triads',
    'Scale notes vs chord tones',
    'Mapping a triad across the neck',
    'maj7, m7 and dominant 7 chord tones',
    'The blues form',
    'm7b5',
    'Major ii–V–I',
    'Voice leading through chord tones',
    'Chromatic approach notes',
    'Note functions and target notes',
  ],
  groove: [
    'Stable quarter and eighth notes',
    'Rests and offbeat entries',
    'Syncopation',
    'Sixteenth subdivisions',
    'Swing feel',
    'Click on 2 and 4',
    'Playing with backing tracks',
    'Raising tempo only when controlled',
  ],
  ear: [
    'Hear and sing a short bass motif',
    'Transcribe the rhythm first',
    'Find a recorded root pattern',
    'Hear 1–2 bars of triads',
    'Extend a transcription',
    'Recover a learned line from memory',
    'Write a heard line as notes or degrees',
    'Pitched vs muted notes in a funk phrase',
    'Full-song transcription project',
    'An unfamiliar phrase by ear',
  ],
  creativity: [
    'Build a two-bar groove from song notes',
    'Vary a groove while keeping the pulse',
    'Fills',
    'A short walking line over a blues',
    'Vary one ending',
    'Two different connections between chords',
    'Walking line across a section of a standard',
    'An original groove',
  ],
  fun: [
    'An easy favourite riff',
    'Connect two fragments without stopping',
    'A song section with its real rests',
    'Link verse and chorus',
    'A faster fragment below original speed',
    'Roots and fifths over a blues backing',
    'A slap groove in a favourite style',
    'Learn the form of a jazz standard',
    'Growth or Dream song in sections',
    'Play a whole song through',
  ],
}
